version: "3.8"

services:
  traefik:
    image: traefik:v2.9
    env_file:
      - .env
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_API_URL_UNAUTHORIZED: ${VITE_API_URL_UNAUTHORIZED}
        VITE_BASE_URL: ${VITE_BASE_URL}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.main.entrypoints=websecure"
      - "traefik.http.routers.main.tls.certresolver=le"
      - "traefik.http.services.main.loadbalancer.server.port=80"
